### ISSUE TITLE
Percentage Decimal points

### ISSUE THREAD

**Issue by dn4086** [jdharrisnz/datorama-d3-river-breakdown#1]
Hey Josh,
Do you know where I can control the number of decimal points on this? I want it to have 0 decimal points for my viz and would like to know where I can achieve it by changing the code on the .js file.

**Comment by jdharrisnz** [comment]
Hi Dan,

For this you just need to edit your measurement settings in the widget. Nothing in the code needs to change.

Thanks,
Josh
